#!/usr/bin/env python3
"""
fishing_server.py  -  Persistent HTTP server for the fishing conditions report
Serves the HTML report generated by fishing_report.py on port 7070.
Reads the file from disk on every request so cron updates appear immediately.

USAGE
-----
  python3 /opt/fishing/fishing_server.py          # manual
  @reboot sleep 10 && python3 /opt/fishing/fishing_server.py >> /var/log/fishing_server.log 2>&1 &

SYSTEMD (save to /etc/systemd/system/fishing-report.service)
-------------------------------------------------------------
  [Unit]
  Description=Pikeminnow Fishing Report Server
  After=network.target

  [Service]
  Type=simple
  User=alan
  ExecStart=/usr/bin/python3 /opt/fishing/fishing_server.py
  Restart=always
  RestartSec=5

  [Install]
  WantedBy=multi-user.target

  sudo systemctl enable --now fishing-report

ACCESS
------
  http://localhost:7070
  http://<tailscale-ip>:7070       (works across Tailscale mesh)
"""

import json
import os
import sys
from datetime import datetime
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from zoneinfo import ZoneInfo

LOCAL_TZ = ZoneInfo("America/Los_Angeles")

# DATA_DIR: state location. /data on Railway; project dir locally.
DATA_DIR    = Path(os.environ.get("DATA_DIR", str(Path(__file__).resolve().parent)))
PORT        = int(os.environ.get("PORT", "7070"))
BIND_HOST   = os.environ.get("BIND_HOST", "0.0.0.0")
_DEFAULT_HTML = DATA_DIR / "report.html"
REPORT_FILE = Path(os.environ.get("FISHING_HTML", str(_DEFAULT_HTML)))
BIND_ADDR   = BIND_HOST  # back-compat alias
STALE_HOURS = 26  # report regenerates daily at 05:30; warn after ~1 missed run

PLACEHOLDER_HTML = """<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Fishing Report - Initializing</title>
<style>
  body{background:#0a0e12;color:#4dd9ac;font-family:monospace;
       display:flex;align-items:center;justify-content:center;
       height:100vh;margin:0;flex-direction:column;gap:16px}
  p{color:#4a6a7a;font-size:12px}
  code{color:#2e6a7a;font-size:11px}
</style></head>
<body>
  <div style="font-size:14px;letter-spacing:.2em">[+] FISHING REPORT</div>
  <p>Report not yet generated.</p>
  <p>Run once to initialise:</p>
  <code>python3 /opt/fishing/fishing_report.py</code>
  <p>Cron regenerates daily at 05:30.</p>
</body></html>"""


def _inject_freshness_banner(html_bytes: bytes, mtime: datetime) -> bytes:
    age = datetime.now(LOCAL_TZ) - mtime
    age_h = age.total_seconds() / 3600
    stale = age_h > STALE_HOURS
    bg = "#7a2e2e" if stale else "#1a3a4a"
    fg = "#ffb4b4" if stale else "#4dd9ac"
    label = "STALE — last update " if stale else "Report generated "
    if age_h < 1:
        age_str = f"{int(age.total_seconds() / 60)} min ago"
    elif age_h < 48:
        age_str = f"{age_h:.1f} h ago"
    else:
        age_str = f"{int(age_h / 24)} days ago"
    banner = (
        f'<div style="position:fixed;top:0;left:0;right:0;z-index:9999;'
        f'background:{bg};color:{fg};font-family:monospace;font-size:12px;'
        f'padding:6px 12px;text-align:center;border-bottom:1px solid #000">'
        f'{label}{mtime:%a %b %-d %-I:%M %p} ({age_str})'
        f'</div>'
    ).encode("utf-8")
    idx = html_bytes.find(b"<body")
    if idx == -1:
        return banner + html_bytes
    end = html_bytes.find(b">", idx)
    if end == -1:
        return banner + html_bytes
    return html_bytes[:end + 1] + banner + html_bytes[end + 1:]


class ReportHandler(BaseHTTPRequestHandler):

    def _send(self, status, body, ctype="text/html; charset=utf-8", cors=False):
        if isinstance(body, str):
            body = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        if cors:
            self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        try:
            self.wfile.write(body)
        except (BrokenPipeError, ConnectionResetError):
            pass

    def do_GET(self):
        if self.path == "/favicon.ico":
            self._send(204, b"", ctype="image/x-icon")
            return

        if self.path == "/health":
            ok = REPORT_FILE.exists()
            payload = {
                "ok": ok,
                "report_file": str(REPORT_FILE),
                "size": REPORT_FILE.stat().st_size if ok else 0,
                "mtime": (datetime.fromtimestamp(REPORT_FILE.stat().st_mtime, tz=LOCAL_TZ)
                          .isoformat(timespec="seconds")) if ok else None,
                "now": datetime.now(LOCAL_TZ).isoformat(timespec="seconds"),
            }
            self._send(200, json.dumps(payload, indent=2),
                       ctype="application/json", cors=True)
            return

        if self.path == "/robots.txt":
            host = self.headers.get("Host", "pikeminnow.pnwbite.com")
            body = (
                "User-agent: *\n"
                "Allow: /\n"
                "Disallow: /health\n\n"
                f"Sitemap: https://{host}/sitemap.xml\n"
            ).encode()
            self._send(200, body, ctype="text/plain; charset=utf-8")
            return

        if self.path == "/sitemap.xml":
            host = self.headers.get("Host", "pikeminnow.pnwbite.com")
            body = (
                '<?xml version="1.0" encoding="UTF-8"?>\n'
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
                '  <url>\n'
                f'    <loc>https://{host}/</loc>\n'
                '    <changefreq>daily</changefreq>\n'
                '    <priority>1.0</priority>\n'
                '  </url>\n'
                '</urlset>\n'
            ).encode()
            self._send(200, body, ctype="application/xml; charset=utf-8")
            return

        if self.path not in ("/", "/index.html", "/report.html"):
            self._send(404, b"Not found", ctype="text/plain; charset=utf-8")
            return

        if REPORT_FILE.exists():
            content = _inject_freshness_banner(
                REPORT_FILE.read_bytes(),
                datetime.fromtimestamp(REPORT_FILE.stat().st_mtime, tz=LOCAL_TZ),
            )
        else:
            content = PLACEHOLDER_HTML.encode("utf-8")
        self._send(200, content)

    def log_message(self, fmt, *args):
        print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {self.address_string()} - {fmt % args}")


def main():
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] Fishing report server starting")
    print(f"  Port  : {PORT}")
    print(f"  File  : {REPORT_FILE}")
    print(f"  Access: http://localhost:{PORT}")
    print(f"          http://<tailscale-ip>:{PORT}")
    if not REPORT_FILE.exists():
        print(f"  NOTE  : Report not found - placeholder served until first run")
    else:
        mtime = datetime.fromtimestamp(REPORT_FILE.stat().st_mtime, tz=LOCAL_TZ)
        print(f"  Ready : last report {mtime:%Y-%m-%d %H:%M}")
    print()

    server = HTTPServer((BIND_ADDR, PORT), ReportHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print(f"\n[{datetime.now():%Y-%m-%d %H:%M:%S}] Server stopped.")
        server.server_close()


if __name__ == "__main__":
    main()
